version: "3.9"

volumes:
  postgres_data:

services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .db.env
  web:
    build: ./app
    volumes:
      - ./app:/opt
    entrypoint: daphne messenger_project.asgi:application -b 0.0.0.0 -p 8000
    env_file:
      - .web.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
      - redis
  migrations:
    build: ./app
    volumes:
      - ./app:/opt
    entrypoint: bash -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput"
    env_file:
      - .web.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
